// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9NRpECQKmJUyG86h4pTZ-_icDu2lTowo',
    appId: '1:980709823238:web:27649ea66598b05bb10487',
    messagingSenderId: '980709823238',
    projectId: 'npfuturegate',
    authDomain: 'npfuturegate.firebaseapp.com',
    storageBucket: 'npfuturegate.firebasestorage.app',
    measurementId: 'G-D87RW2J8JJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZG7eV6wKRBDbITzmLB_RV3_3-7H3z1Dw',
    appId: '1:980709823238:android:311dc3de1e9ed0edb10487',
    messagingSenderId: '980709823238',
    projectId: 'npfuturegate',
    storageBucket: 'npfuturegate.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiVsvjI09N-T5bDf4BhhBLg3UHsvmmW2g',
    appId: '1:980709823238:ios:8094e414624a807db10487',
    messagingSenderId: '980709823238',
    projectId: 'npfuturegate',
    storageBucket: 'npfuturegate.firebasestorage.app',
    iosBundleId: 'com.example.npFutureGate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiVsvjI09N-T5bDf4BhhBLg3UHsvmmW2g',
    appId: '1:980709823238:ios:8094e414624a807db10487',
    messagingSenderId: '980709823238',
    projectId: 'npfuturegate',
    storageBucket: 'npfuturegate.firebasestorage.app',
    iosBundleId: 'com.example.npFutureGate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9NRpECQKmJUyG86h4pTZ-_icDu2lTowo',
    appId: '1:980709823238:web:ecf4e4c7421bd833b10487',
    messagingSenderId: '980709823238',
    projectId: 'npfuturegate',
    authDomain: 'npfuturegate.firebaseapp.com',
    storageBucket: 'npfuturegate.firebasestorage.app',
    measurementId: 'G-KBE85VLYMS',
  );
}
